openapi: 3.0.0
info:
  title: Input Grade
  version: 1.0.0

tags:
  - name: Daftar API

parameters:
  - in: body
    name: body
    description: Grade yang akan ditambahkan
    required: true
    schema:
      $ref: '#/definitions/Grades'

responses:
  201:
    description: Data Siswa Berhasil ditambahkan
    schema:
      $ref: '#/definitions/Grades'

definitions:
  Grades:
    type: object
    properties:
      subject_name:
        type: string
      score:
        type: float
      date:
        type: string
        minLength: 8
        maxLength: 8
        format: date
        pattern: '^\d{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$'
        example: 2019-08-16
        description: Birth date of the  member in YYYY-MM-DD format.
    required:
      - subject_name
      - score
      - date
 