openapi: 3.0.0
info:
  title: Input Grade
  version: 1.0.0

tags:
  - name: Daftar API

parameters:
  - in: body
    name: body
    description: Grade yang akan ditambahkan
    required: true
    schema:
      $ref: '#/definitions/Grades'

responses:
  201:
    description: Data Siswa Berhasil ditambahkan
    schema:
      $ref: '#/definitions/Grades'

definitions:
  Grades:
    type: object
    properties:
      student_id:
        type: integer
      subject_name:
        type: string
      score:
        type: number
      date:
        type: string
        minLength: 8
        maxLength: 8
        format: date
    required:
      - student_id
      - subject_name
      - score
      - date
 