openapi: 3.0.0
info:
  title: Input data student
  version: 1.0.0

tags:
  - name: Daftar API

parameters:
  - in: body
    name: body
    description: Data Siswa yang akan ditambahkan
    required: true
    schema:
      $ref: '#/definitions/Students'

responses:
  201:
    description: Data Siswa Berhasil ditambahkan
    schema:
      $ref: '#/definitions/Students'

definitions:
  Students:
    type: object
    properties:
      name:
        type: string
      student_class:
        type: string
    required:
      - name
      - student_class
 