openapi: 3.0.0
info:
  title: Ambil Semua Data Siswa
  version: 1.0.0
tags:
  - name: Daftar API 

responses: #Daftar respon yang dapat diberikan oleh operasi API 
  200: #kode status HTTP untuk respon sukses
    description: Data Siswa berhasil ditambahkan
    schema:
      type: array
      items:
        $ref: '#/definitions/Students'

definitions: #Daftar definisi skema yang dapat digunakan diseluruh file
  Students: #Nama dari definisi skema
    type: object #Tipe dari skema, dalam hal ini adalah object
    properties: #Daftar propertie yang dapat dimiliki oleh object
      student_id:
        type: integer
        description: Student Id
      name:
        type: string
        description: Student Name
      student_class:
        type: string
        description: Student Class
      grade:
        type: string
        description: Student Grade
    

